### ISSUE TITLE
check option

### ISSUE THREAD

**Issue by darky** [jamestalmage/istanbul-combine#1]
I try to use [check option](https://github.com/karma-runner/karma-coverage/blob/master/docs/configuration.md#check) to set minimum percentage required. But no error raised in callback or promise...

**Comment by jamestalmage** [comment]
That's a karma coverageReporter option. While this can be used to combine the output from multiple karma runs (I frequently use it to do just that), it really has nothing to do with karma.

It will pass options to any of the [istanbul reporters](https://github.com/gotwarlost/istanbul/tree/master/lib/report) you specify, but I don't see `check` as an available option for any of those (I only glanced at a couple just now).

You could probably use the `json-summary` reporter, and write your own code to check all the appropriate values and exit with an error if it doesn't meet the threshold.

**Comment by jamestalmage** [comment]
You actually don't need this lib to do this, just do:

```
istanbul check-coverage --statements 90 **/*coverage.json
```

**Comment by darky** [comment]
Thank's you!
