### ISSUE TITLE
Generating html report after merging coverage information

### ISSUE THREAD

**Issue by VladyslavKurmaz** [jamestalmage/istanbul-combine#13]
I've started seeing this issue a couple days ago. A week ago everything worked smoothly. Looks like our js source code was changed and somehow uncovered this bug.
```
    "istanbul": "^0.4.5",
    "istanbul-combine": "^0.3.0"
```
We are combining coverage from a set of files. Looks like calculation is fine, but the report generation is failed
```
=============================== Coverage summary ===============================
Statements   : 29.37% ( 1614/5496 )
Branches     : 9.96% ( 442/4436 )
Functions    : 28.57% ( 932/3262 )
Lines        : 30.26% ( 1276/4217 )
================================================================================
node_modules/istanbul-combine/node_modules/istanbul/lib/report/html.js:283
                    text = structuredText[startLine].text;
```
Another possible reason can be that we switched from angulajs-1.7.0 to angularjs-1.7.3 a month ago

https://github.com/gotwarlost/istanbul/issues/817

**Comment by VladyslavKurmaz** [comment]
Please close the issue, the root cause was with synchronization between source code and coverage information.

**Comment by ns89-web** [comment]
> Please close the issue, the root cause was with synchronization between source code and coverage information.

I am facing similar issues, can you please explain how you fixed this problem?
