### ISSUE TITLE
Feature Request - Add support for Istanbul config files when using command line

### ISSUE THREAD

**Issue by ChrisPearce** [jamestalmage/istanbul-combine#3]
It would be very helpful for the command line to be able to process a .istanbul.yml config file.

One use case for this is:
- allowing the user to specify the reporter watermark levels when using the command line tool

**Comment by jamestalmage** [comment]
@ChrisPearce 
I'm currently considering deprecating this whole library.

See #2.

Now that the karma bug is fixed, there's really no point to this tool.

Either way, I definitely will not be adding yaml support. I don't want the extra dependency.

That said, sounds like a perfectly reasonable tool, but it should be it's own library.
